version: 2
jobs:
  minecraft_server:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t itzg/minecraft-server:${CIRCLE_BRANCH} .
      - run:
          name: Build arm v7 image
          command: docker build -t itzg/minecraft-server:${CIRCLE_BRANCH}-arm-v7 --platform linux/arm/v7 --build-arg ARCH=armv7 .

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server
