version: 2.1

orbs:
  docker: circleci/docker@0.5.20

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/minecraft-server
          tag: multiarch
          extra_build_args: "--platform linux/amd64,linux/arm64,linux/arm/v7"
          deploy: false

