version: 2
jobs:
  minecraft_server:
    docker:
      - image: circleci/buildpack-deps:18.10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t mc:$CIRCLE_BUILD_NUM minecraft-server
      - run:
          name: Test default version and type
          no_output_timeout: "60s"
          command: |
            docker run -t --rm -e EULA=TRUE mc:$CIRCLE_BUILD_NUM | tee /tmp/docker-run.log | grep "[Server thread/INFO]: Done"
      - store_artifacts:
          path: /tmp/docker-run.log

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server
