version: 2
jobs:
  minecraft_server:
    docker:
      - image: circleci/buildpack-deps:18.10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build minecraft-server

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server
