version: 2.1

orbs:
  docker-buildx: foodles/docker-buildx@0.0.1

workflows:
  version: 2
  build:
    jobs:
      - publish:
          image: itzg/minecraft-server
          tag: "<< pipeline.git.branch >>-test-ci"
          deploy: false
          filters:
            branches:
              ignore:
                - armv7
                - multiarch
