version: 2.1

orbs:
  docker-buildx: foodles/docker-buildx@0.0.1

workflows:
  version: 2
  build:
    jobs:
      - docker-buildx/publish:
          image: itzg/minecraft-server
          tag: "<< pipeline.git.branch >>-test-ci"
          extra_build_args: >-
            --platform=linux/arm64
            --platform=linux/arm/v7
            --platform=linux/amd64
          deploy: false
          filters:
            branches:
              only:
                - multiarch
                - ftba-support
