name: Build and publish multiarch
on:
  push:
    branches:
      - multiarch
      - multiarch-latest
      - test-new-dockerx-build
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-multiarch"
      - "[0-9]+.[0-9]+.[0-9]+-multiarch-latest"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Get branch name
        uses: nelonoel/branch-name@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: false
          tags: |
            itzg/minecraft-server:${{ env.BRANCH_NAME }}
          cache-from: type=registry,ref=itzg/minecraft-server:${{ env.BRANCH_NAME }}
          cache-to: type=inline

