# This is a basic workflow to help you get started with Actions

name: Build and publish non-multiarch branches/tags

on:
  push:
    branches:
      - master
      - openj9
      - openj9-nightly
      - adopt11
      - adopt13
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-openj9"
      - "[0-9]+.[0-9]+.[0-9]+-openj9-nightly"
      - "[0-9]+.[0-9]+.[0-9]+-adopt11"
      - "[0-9]+.[0-9]+.[0-9]+-adopt13"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        repository: itzg/minecraft-server
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        tag_with_sha: true
        cache_froms: itzg/minecraft-server:latest
        add_git_labels: true
        push: true
